### ISSUE TITLE
version conflicts on tensorflow vs dm-reverb vs protobuf ?

### ISSUE THREAD

**Issue by deepcomp2023** [google-deepmind/reverb#108]
Hi, when I run BLE with support of reverb, I got such error message:

```
  File "/data/miniconda/envs/p37ble/lib/python3.7/site-packages/reverb/platform/default/load_op_library.py", line 46, in reraise_wrapped_error
    sys.exc_info()[2])
  File "/data/miniconda/envs/p37ble/lib/python3.7/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/data/miniconda/envs/p37ble/lib/python3.7/site-packages/reverb/pybind.py", line 4, in <module>
    from .libpybind import *
ImportError: 
Attempted to load a reverb dynamic library, but it could not find the required
symbols inside of TensorFlow.  This commonly occurs when your version of
tensorflow and reverb are mismatched.  For example, if you are using the python
package 'tf-nightly', make sure you use the python package 'dm-reverb-nightly'
built on the same or the next night.  If you are using a release version package
'tensorflow', use a release package 'dm-reverb' built to be compatible with
that exact version.  If all else fails, file a github issue on deepmind/reverb.
Current installed version of tensorflow: 2.8.2.

Orignal error:
/data/miniconda/envs/p37ble/lib/python3.7/site-packages/reverb/libschema_cc_proto.so: undefined symbol: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev
```

it makes me confusing, is this related with protobuf package or just reverb?

could you please do me a favor on this?

**Comment by acassirer** [comment]
Hey,

I'm afraid I can't really tell you what the exact issue was without more details but my guess would be that the error message you posted is already giving you the answer. It looks like you are using a Reverb version that is incompatible with tf 2.8.2 and if this is the case then you have two options:

 1. Use Reverb 0.8 (which is compatible with tf 2.8)
 2. Update tensorflow to match your Reverb version.

**Comment by guanjiayi** [comment]
Hi, I have the same problem, I don't know if the latter problem has been solved. I tried adjusting the version of tensorflow and reverb, but still can't solve the problem. Now attach the version of the relevant packages I installed, please help to check the versions of those packages that need to be updated or adjusted.


**The currently installed version of the relevant package**
```
absl-py                       1.3.0
dm-acme                       0.2.2
dm-control                    1.0.8
dm-env                        1.5
dm-haiku                      0.0.4
dm-launchpad                  0.5.2
dm-launchpad-nightly          0.3.0.dev20220413
dm-reverb                     0.7.2
dm-sonnet                     2.0.0
dm-tree                       0.1.6
gym                           0.19.0
jax                           0.3.23
jaxlib                        0.3.22
joint_state_publisher         1.12.15
kdl_parser_py                 1.13.1
keras                         2.10.0
keras-nightly                 2.12.0.dev2022110207
Keras-Preprocessing           1.1.2
tb-nightly                    2.11.0a20221102
tensorboard                   2.10.1
tensorboard-data-server       0.6.0
tensorboard-plugin-wit        1.8.0
tensorflow                    2.10.0
tensorflow-datasets           4.7.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.27.0
tensorflow-metadata           1.10.0
tensorflow-probability        0.18.0
termcolor                     2.1.0
tf                            1.12.1
tf_conversions                1.12.1
tf-estimator-nightly          2.12.0.dev2022110208
tf-nightly                    2.12.0.dev20221102
tf2_geometry_msgs             0.6.5
tf2_kdl                       0.6.5
tf2_py                        0.6.5
tf2_ros                       0.6.5
tfp-nightly                   0.14.0.dev20210818
```

**Comment by WanyingMo** [comment]
I have met this problem also just now QAQ
Anyone help please?

Attempted to load a reverb dynamic library, but it could not find the required
symbols inside of TensorFlow.  This commonly occurs when your version of
tensorflow and reverb are mismatched.  For example, if you are using the python
package 'tf-nightly', make sure you use the python package 'dm-reverb-nightly'
built on the same or the next night.  If you are using a release version package
'tensorflow', use a release package 'dm-reverb' built to be compatible with
that exact version.  If all else fails, file a github issue on deepmind/reverb.
Current installed version of tensorflow: 2.13.0.

tensorflow                       2.13.0
dm-reverb                        0.13.0

**Comment by WanyingMo** [comment]
> I have met this problem also just now QAQ Anyone help please?
> 
> Attempted to load a reverb dynamic library, but it could not find the required symbols inside of TensorFlow. This commonly occurs when your version of tensorflow and reverb are mismatched. For example, if you are using the python package 'tf-nightly', make sure you use the python package 'dm-reverb-nightly' built on the same or the next night. If you are using a release version package 'tensorflow', use a release package 'dm-reverb' built to be compatible with that exact version. If all else fails, file a github issue on deepmind/reverb. Current installed version of tensorflow: 2.13.0.
> 
> tensorflow 2.13.0 dm-reverb 0.13.0

Oh I just solved it by: pip install dm-reverb[tensorflow]

**Comment by pabloskyg** [comment]
The solution @WanyingMo it works well....solved¡. 

Thank you very much.
