### ISSUE TITLE
Reverb fails to install

### ISSUE THREAD

**Issue by ace510** [google-deepmind/reverb#140]
Observed Behavior:
pip install dm-reverb

pip install dm-reverb[tensorflow]
&
pip install dm-reverb-nightly[tensorflow]

all fail with
`
ERROR: Could not find a version that satisfies the requirement dm-reverb (from versions: none)
ERROR: No matching distribution found for dm-reverb
`

Environment: 
Debian 40
Python 3.12.4

**Comment by drakon** [comment]
Try it with python 3.9, 3.10 or 3.11.

**Comment by ace510** [comment]
that got it! thanks
